import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'

import { MantineProvider } from '@mantine/core';

import { AppBody } from '../components/AppBody'

function HomeHead(){
  return (
    <div className={styles.container}>
      <Head>
        <title>Marvel Api Consumer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

const Home: NextPage = () => {
  return (
    <MantineProvider 
      theme={{
        fontFamily: 'Open Sans, sans serif',
        spacing: { xs: 15, sm: 20, md: 25, lg: 30, xl: 40 },
      }}>
      <HomeHead/>

      <AppBody />
    </MantineProvider>
  )
}

export default Home
