import type { NextPage } from 'next'
import { GetStaticProps } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'

import { MantineProvider } from '@mantine/core';
import { AppBody } from '../components/AppBody'

function HomeHead(){
  return (
    <div className={styles.container}>
      <Head>
        <title>Marvel Api Consumer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

interface StaticProps{
  marvelApiKeyPublic: string,
  marvelApiKeyPrivate: string
}

const Home: NextPage<StaticProps> = (props: StaticProps) => {
  return (
    <MantineProvider 
      theme={{
        fontFamily: 'Open Sans, sans serif',
        spacing: { xs: 15, sm: 20, md: 25, lg: 30, xl: 40 },
      }}>
      <HomeHead/>

      <AppBody
        marvelApiKeyPublic={props.marvelApiKeyPublic}
        marvelApiKeyPrivate={props.marvelApiKeyPrivate}
      />
    </MantineProvider>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async(context) => {
  return {
    props: {
      marvelApiKeyPublic: process.env.PUBLIC_KEY,
      marvelApiKeyPrivate: process.env.PRIVATE_KEY
    },
  }
}

export type { StaticProps }